### ISSUE TITLE
Add font-display: option to Henris font include

### ISSUE THREAD

**Issue by dipsaus9** [henris-style/typography#30]
https://github.com/henris-style/typography/blob/e64e353a7acacdb07a5387d9e774a456b4736550/src/load/_load.scss#L43

**Comment by dipsaus9** [comment]
Preferably with a option to each font. So primary font's can be loaded faster then secondary.

**Comment by mmeester** [comment]
@dipsaus9 can you give a little more background on this?

**Comment by dipsaus9** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
Highly encouraged by google. But you don't want a default setting. Preferable with an option under the font-style.
